# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "authors", :force => true do |t|
    t.integer  "data_source_id"
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "person_id"
    t.integer  "authority_id"
  end

  create_table "authorships", :force => true do |t|
    t.integer  "author_id"
    t.integer  "citation_id"
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "authorships", ["author_id"], :name => "author_id"
  add_index "authorships", ["citation_id"], :name => "citation_id"

  create_table "citations", :force => true do |t|
    t.string   "type"
    t.string   "title_primary"
    t.string   "title_secondary"
    t.string   "title_tertiary"
    t.string   "affiliation"
    t.string   "year"
    t.string   "volume"
    t.string   "issue"
    t.string   "start_page"
    t.string   "end_page"
    t.text     "abstract"
    t.text     "notes"
    t.string   "links"
    t.string   "citation_archive_uri"
    t.string   "title_dupe_key"
    t.string   "issn_isbn_dupe_key"
    t.integer  "citation_state_id"
    t.integer  "citation_archive_state_id"
    t.integer  "publication_id"
    t.integer  "publisher_id"
    t.integer  "imported_for"
    t.integer  "bump_value"
    t.datetime "archived_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "data_source_id"
    t.integer  "external_id"
    t.text     "serialized_data"
    t.text     "original_data"
  end

  add_index "citations", ["title_dupe_key"], :name => "title_dupe_key"
  add_index "citations", ["issn_isbn_dupe_key"], :name => "issn_isbn_dupe_key"
  add_index "citations", ["citation_state_id"], :name => "citation_state_id"
  add_index "citations", ["publication_id"], :name => "publication_id"
  add_index "citations", ["publisher_id"], :name => "publisher_id"
  add_index "citations", ["type"], :name => "type"

  create_table "groups", :force => true do |t|
    t.string   "name"
    t.string   "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "keywordings", :force => true do |t|
    t.integer  "keyword_id"
    t.integer  "citation_id"
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "keywords", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "memberships", :force => true do |t|
    t.integer  "person_id"
    t.integer  "group_id"
    t.string   "title"
    t.boolean  "active"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "position"
  end

  create_table "pen_names", :force => true do |t|
    t.integer  "author_id"
    t.integer  "person_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "people", :force => true do |t|
    t.integer  "external_id"
    t.string   "first_name"
    t.string   "middle_name"
    t.string   "last_name"
    t.string   "prefix"
    t.string   "suffix"
    t.string   "image_url"
    t.string   "phone"
    t.string   "email"
    t.string   "im"
    t.string   "office_address_line_one"
    t.string   "office_address_line_two"
    t.string   "office_city"
    t.string   "office_state"
    t.string   "office_zip"
    t.text     "research_focus"
    t.boolean  "active"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "publications", :force => true do |t|
    t.integer  "sherpa_id"
    t.integer  "publisher_id"
    t.integer  "source_id"
    t.integer  "authority_id"
    t.string   "name"
    t.string   "url"
    t.string   "code"
    t.string   "issn_isbn"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "place"
  end

  add_index "publications", ["publisher_id"], :name => "publisher_id"
  add_index "publications", ["authority_id"], :name => "authority_id"

  create_table "publishers", :force => true do |t|
    t.integer  "sherpa_id"
    t.integer  "source_id"
    t.integer  "authority_id"
    t.boolean  "publisher_copy"
    t.string   "name"
    t.string   "url"
    t.string   "romeo_color"
    t.string   "copyright_notice"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "publishers", ["authority_id"], :name => "authority_id"

  create_table "taggings", :force => true do |t|
    t.integer  "tag_id"
    t.integer  "taggable_id"
    t.string   "taggable_type"
    t.datetime "created_at"
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.string "name"
  end

end
