#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "rbibtex.y".
#

require 'racc/parser'



module BibTeX
  Entry = Struct.new(:type, :key, :properties)
end


module BibTeX

  class Parser < Racc::Parser

module_eval <<'..end rbibtex.y modeval..id51db1184c7', 'rbibtex.y', 115

  def report(*args)
    p args
  end
  
  def parse( str )
    @q = []

    @yydebug = true

    while str.size > 0 do
      case str
      when /\A[\t\n\s]+/o
        @q.push [:SPACE, $&]
      when /\ACOMMENT/o
        @q.push [:COMMENT, $&]
      when /\A\,/o
        @q.push [:COMMA, $&]
      when /\A@/o
        @q.push [:AT, $&]
      when /\A\{/o
        @q.push [:LBRACE, $&]
      when /\A\}/o
        @q.push [:RBRACE, $&]
      when /\A\=/o
        @q.push [:EQUALS, $&]
      when /\A\'/o
        @q.push [:SINGLE_ANFZ, $&]
      when /\A\"/o
        @q.push [:DOUBLE_ANFZ, $&]
      when /\A\w+/o
        @q.push [:WORD, $&]
      when /\A./o
        @q.push [:CHARACTER, $&]
      when /\A\d+/o
        @q.push [:NUMBER, $&.to_i]
      end
      str = $'
    end
    @q.push [false, '$end']

    do_parse
  end

  def next_token
    @q.shift
  end


..end rbibtex.y modeval..id51db1184c7

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 14, :_reduce_1,
 3, 14, :_reduce_2,
 1, 16, :_reduce_3,
 3, 16, :_reduce_4,
 3, 17, :_reduce_5,
 1, 18, :_reduce_6,
 1, 18, :_reduce_7,
 3, 19, :_reduce_8,
 3, 20, :_reduce_9,
 5, 20, :_reduce_10,
 2, 20, :_reduce_11,
 8, 22, :_reduce_12,
 1, 24, :_reduce_none,
 0, 25, :_reduce_14,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 2, 25, :_reduce_17,
 2, 25, :_reduce_18,
 1, 23, :_reduce_19,
 4, 23, :_reduce_20,
 6, 26, :_reduce_21,
 1, 27, :_reduce_none,
 3, 21, :_reduce_23,
 3, 21, :_reduce_24,
 3, 21, :_reduce_25,
 1, 21, :_reduce_none,
 0, 29, :_reduce_27,
 2, 29, :_reduce_28,
 2, 29, :_reduce_29,
 2, 29, :_reduce_30,
 2, 29, :_reduce_31,
 2, 29, :_reduce_32,
 2, 29, :_reduce_33,
 2, 29, :_reduce_34,
 2, 29, :_reduce_35,
 0, 30, :_reduce_36,
 2, 30, :_reduce_37,
 2, 30, :_reduce_38,
 2, 30, :_reduce_39,
 2, 30, :_reduce_40,
 2, 30, :_reduce_41,
 2, 30, :_reduce_42,
 2, 30, :_reduce_43,
 2, 30, :_reduce_44,
 0, 28, :_reduce_45,
 2, 28, :_reduce_46,
 2, 28, :_reduce_47,
 2, 28, :_reduce_48,
 2, 28, :_reduce_49,
 2, 28, :_reduce_50,
 2, 28, :_reduce_51,
 2, 28, :_reduce_52,
 4, 28, :_reduce_53,
 0, 15, :_reduce_none,
 1, 15, :_reduce_none ]

racc_reduce_n = 56

racc_shift_n = 85

racc_action_table = [
    51,    58,    52,    53,    54,    55,    56,    29,    57,    49,
    50,    60,     1,    83,    62,    63,    64,    65,     1,    66,
    49,    59,    60,    36,    61,    62,    63,    64,    65,     1,
    66,    49,    59,    69,   -36,    70,    71,    72,    73,    74,
   -27,    66,    67,    68,    31,    32,    78,    79,    33,    30,
    13,     1,    31,    32,    14,    21,    33,    30,    23,    44,
    47,    48,    23,    26,    27,     1,     1,     5,     1,     1,
     1,     1,    75,     8,     5,   -37,   -42,   -39,   -43,   -38,
   -41,   -40,   -31,   -28,   -33,   -30,   -34,   -29,   -32,     1,
    82,     4,     1 ]

racc_action_check = [
    38,    39,    38,    38,    38,    38,    38,    24,    38,    38,
    38,    80,    13,    80,    80,    80,    80,    80,    27,    80,
    80,    80,    40,    28,    40,    40,    40,    40,    40,    29,
    40,    40,    40,    41,    30,    41,    41,    41,    41,    41,
    33,    41,    41,    41,    45,    45,    46,    46,    45,    45,
     9,    46,    25,    25,     9,    11,    25,    25,    11,    35,
    37,    37,    35,    19,    19,    12,    36,    10,     0,    22,
     6,     5,    42,     4,     3,    50,    51,    53,    54,    55,
    56,    57,    67,    68,    69,    71,    72,    73,    74,    76,
    77,     2,    82 ]

racc_action_pointer = [
    56,   nil,    91,    72,    73,    59,    58,   nil,   nil,    47,
    65,    51,    53,     0,   nil,   nil,   nil,   nil,   nil,    59,
   nil,   nil,    57,   nil,     1,    46,   nil,     6,    14,    17,
    23,   nil,   nil,    30,   nil,    55,    54,    53,    -2,   -10,
    20,    31,    62,   nil,   nil,    38,    39,   nil,   nil,   nil,
    64,    65,   nil,    66,    67,    68,    69,    70,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    72,    73,    74,
   nil,    75,    76,    77,    78,   nil,    77,    85,   nil,   nil,
     9,   nil,    80,   nil,   nil ]

racc_action_default = [
   -54,   -55,   -56,    -1,   -56,   -54,   -54,    -3,    85,   -56,
    -2,   -56,   -54,   -54,   -13,    -5,    -6,    -7,    -4,   -56,
   -19,   -11,   -54,   -22,   -56,   -56,    -9,   -54,   -56,   -54,
   -45,   -45,   -26,   -45,    -8,   -56,   -54,   -14,   -56,   -56,
   -56,   -56,   -56,   -20,   -10,   -56,   -54,   -16,   -15,   -50,
   -46,   -52,   -44,   -48,   -45,   -47,   -51,   -49,   -25,   -46,
   -52,   -23,   -48,   -45,   -47,   -51,   -49,   -50,   -46,   -52,
   -35,   -48,   -45,   -47,   -51,   -24,   -54,   -56,   -18,   -17,
   -56,   -21,   -54,   -53,   -12 ]

racc_goto_table = [
     3,    20,     7,    34,    11,     9,    10,    38,    40,    18,
    41,    17,    24,    25,    15,    16,    19,    12,    46,     6,
     2,    42,    28,    76,    39,    43,   nil,    35,   nil,    37,
   nil,   nil,   nil,   nil,   nil,   nil,    45,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    77,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    81,   nil,   nil,   nil,
   nil,   nil,    84 ]

racc_goto_check = [
     2,    13,     4,     8,     9,     2,     2,    15,    15,     4,
    15,     7,     2,     2,     5,     6,    10,    11,    12,     3,
     1,    16,     2,     8,    17,    13,   nil,     2,   nil,     2,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    20,     0,    16,    -1,     5,     6,     2,   -22,    -5,
     5,     8,   -19,   -10,   nil,   -23,   -12,    -6 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    22,    80,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :AT => 2,
 :COMMENT => 3,
 :RBRACE => 4,
 :COMMA => 5,
 :LBRACE => 6,
 :WORD => 7,
 :CHARACTER => 8,
 :EQUALS => 9,
 :SINGLE_ANFZ => 10,
 :DOUBLE_ANFZ => 11,
 :SPACE => 12 }

racc_use_result_var = true

racc_nt_base = 13

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'AT',
'COMMENT',
'RBRACE',
'COMMA',
'LBRACE',
'WORD',
'CHARACTER',
'EQUALS',
'SINGLE_ANFZ',
'DOUBLE_ANFZ',
'SPACE',
'$start',
'file',
'opt_space',
'object_list',
'object',
'at_object',
'comment',
'entry',
'value',
'entry_head',
'assignment_list',
'entry_name',
'key_name',
'assignment',
'assignment_lhs',
'value_content',
'value_content_single_del',
'value_content_double_del']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'rbibtex.y', 4
  def _reduce_1( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 5
  def _reduce_2( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 8
  def _reduce_3( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 9
  def _reduce_4( val, _values, result )
 result << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 12
  def _reduce_5( val, _values, result )
 result = val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 15
  def _reduce_6( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 16
  def _reduce_7( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 19
  def _reduce_8( val, _values, result )
 result = [:comment, val[2]]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 23
  def _reduce_9( val, _values, result )
 val[0].properties = val[1]; result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 25
  def _reduce_10( val, _values, result )
 val[0].properties = val[1]; result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 26
  def _reduce_11( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 32
  def _reduce_12( val, _values, result )
 result = Entry.new(val[0], val[4])
   result
  end
.,.,

 # reduce 13 omitted

module_eval <<'.,.,', 'rbibtex.y', 38
  def _reduce_14( val, _values, result )
 result = ""
   result
  end
.,.,

 # reduce 15 omitted

 # reduce 16 omitted

module_eval <<'.,.,', 'rbibtex.y', 41
  def _reduce_17( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 42
  def _reduce_18( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 45
  def _reduce_19( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 47
  def _reduce_20( val, _values, result )
 result.merge!(val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 52
  def _reduce_21( val, _values, result )
 result = {val[0].downcase.to_sym => val[4]}
   result
  end
.,.,

 # reduce 22 omitted

module_eval <<'.,.,', 'rbibtex.y', 58
  def _reduce_23( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 59
  def _reduce_24( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 60
  def _reduce_25( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 26 omitted

module_eval <<'.,.,', 'rbibtex.y', 64
  def _reduce_27( val, _values, result )
 result = ""
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 65
  def _reduce_28( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 66
  def _reduce_29( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 67
  def _reduce_30( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 69
  def _reduce_31( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 70
  def _reduce_32( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 71
  def _reduce_33( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 72
  def _reduce_34( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 73
  def _reduce_35( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 76
  def _reduce_36( val, _values, result )
 result = ""
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 77
  def _reduce_37( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 78
  def _reduce_38( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 79
  def _reduce_39( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 80
  def _reduce_40( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 82
  def _reduce_41( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 83
  def _reduce_42( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 84
  def _reduce_43( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 85
  def _reduce_44( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 88
  def _reduce_45( val, _values, result )
 result = ""
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 89
  def _reduce_46( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 90
  def _reduce_47( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 91
  def _reduce_48( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 92
  def _reduce_49( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 93
  def _reduce_50( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 94
  def _reduce_51( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 95
  def _reduce_52( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'rbibtex.y', 97
  def _reduce_53( val, _values, result )
 result << val[1] << val[2] << val[3]
   result
  end
.,.,

 # reduce 54 omitted

 # reduce 55 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module BibTeX
