production:
  solr:
    hostname: localhost
    port: 18983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 18982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 18981
    log_level: WARNING