#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

puts "\n**** This is gonna take a long time. Word to yr mother.\n\n"

Dir.glob("tmp/batch_import/*xml") do |file|
  person_id = File.basename(file, ".xml").to_i
  person = Person.find(person_id)
  puts "Processing file #{file} for #{person.display_name} (#{person.id})"
  data = File.read(file)
  Authorship.create_batch!(person, data)
end