#!/usr/bin/env ruby
begin
  require 'rubygems'
  require_gem 'Bloglines4R'
rescue LoadError
  require 'bloglines'
end

require File.dirname(__FILE__) + '/../config/environment'

# Bloglines accounts are stored in config > bloglines.yml
# Here we grok all the accounts

confs = YAML.load_file(File.join(RAILS_ROOT, 'config', 'bloglines.yml'))

@posts = Array.new

# For each account, create a connection
confs.each do |conn|
  init = Bloglines::WebServices.new(:user => conn[1]['email'], :password => conn[1]['password'])
  @feeds = init.listsubs
  
  # For each feed in the account, look for new posts
  @feeds.elements.each("opml/body/outline/outline") do |o|
    # It seems expensive to obtain the Person object, but it really isn't...
    # This method is slow from remote calling and loading xml
    person = Person.find_by_id(o.attributes["title"].split('|')[1])
    folder = o.attributes["BloglinesSubId"]
    add = init.getitems(folder)
    
    # Add new posts to the feeds table
    add.elements.each("//item") do |item|
      @posts << Feed.from_bloglines_xml(person, item)
    end
  end
end