#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
puts "DELAYED JOB ENV #{ENV['RAILS_ENV']}"
puts "ARGUMENTS: #{ARGV.join(':')}"
Delayed::Command.new(ARGV).daemonize
