#!/usr/bin/env ruby

puts "\n**** This is gonna take a long time. It may also irritate the SHERPA people.\n\n"

require File.dirname(__FILE__) + '/../config/environment'

x = Publisher.from_sherpa_api("www.sherpa.ac.uk","/romeoapi11.php?all=yes")

@issns = Citation.find_by_sql(
  "select distinct c.issn_isbn as issn, c.*
  from citations c
  where reftype_id in (1,5)
  and character_length(c.issn_isbn) < 10
  and c.issn_isbn not in (select issn_isbn from publications)
  and c.issn_isbn != ''
  group by issn_isbn
  order by issn_isbn"
)

@issns.each do |pub|
  var = "/romeoapi11.php?issn=" + pub.issn
  Publication.from_sherpa_api("www.sherpa.ac.uk", var)
  sleep 0.15
end

Publisher.find(:all).each do |publisher|
  publisher.save
end